apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    harnesscd.harnessproj.io/hook: PreSync
    harnesscd.harnessproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
