apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
  annotations:
    harnesscd.harnessproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-hooks
  annotations:
    harnesscd.harnessproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-guestbook
  annotations:
    harnesscd.harnessproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: sync-waves
  annotations:
    harnesscd.harnessproj.io/sync-wave: "-1"
