apiVersion: harnessproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: harnesscd
  finalizers:
  - resources-finalizer.harnesscd.harnessproj.io
spec:
  destination:
    namespace: sync-waves
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sync-waves
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
